/// DEPRECATED: Do not edit this file.
/// App version is now dynamically loaded from pubspec.yaml via `PackageInfo`.
@Deprecated('Use PackageInfo.fromPlatform() or pubspec.yaml instead')
const String appVersion = '2.0.1';
